name: Dreamer
env: walker_run
ckpt_callback:
  save_top_k: 1
  mode: min
  monitor: loss
  save_on_train_epoch_end: True
trainer_params:
  default_root_dir: None
  gpus: 1
  gradient_clip_val: 100.0
  val_check_interval: 5
  max_epochs: 1000
dreamer:
  td_model_lr: 1.0e-3
  actor_lr: 5.0e-4
  critic_lr: 5.0e-4
  default_lr: 1.0e-5
  weight_decay: 1.0e-4
  
  batch_size: 64
  batch_length: 50
  length: 50
  prefill_episodes: 10
  prefill_timesteps: 5000
  explore_noise: 0.3
  max_episode_length: 1000
  collect_interval: 100
  max_experience_length: 1000
  save_episodes: False
  
  discount: 0.99
  lambda: 0.95
  clip_actions: False
  horizon: 1000
  imagine_horizon: 15
  free_nats: 3.0
  kl_coeff: 1.0

  dreamer_model:
      obs_space: [3, 64, 64]
      action_space: [0, 0, 0, 0, 0, 0]
      num_outputs: 1
      custom_model: DreamerModel
      deter_size: 200
      stoch_size: 30
      depth_size: 32
      hidden_size: 400
      action_init_std: 5.0
  env_config:
      action_repeat: 2